name: Pull request tests for normie
on:
   - pull_request

jobs:
  testing:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.11.9, 3.12.8, 3.13.1]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./normie
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Test package
        run: poetry run test
