name: Deploy normie prerelease to pypi
on:
  push:
    branches: 
      - "**"

jobs:
  publish_wheel:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.11",]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./normie
    if: "contains(github.event.head_commit.message, 'Prerelease')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Build package
        run: poetry build -f wheel
      - name: Test package
        run: poetry run test
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.NORMIE_PYPI_TOKEN }}

  publish_sdist:
    strategy:
      fail-fast: false
    runs-on: ubuntu-24.04
    defaults:
      run:
        working-directory: ./normie
    if: "contains(github.event.head_commit.message, 'Prerelease')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: 3.12
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install
      - name: Build package
        run: poetry build -f sdist
      - name: Test package
        run: poetry run test
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.NORMIE_PYPI_TOKEN }}
