name: Deploy normie wheels to pypi
on:
  push:
    branches: 
      - main
      - build_wheels

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [arm64, x64]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./normie
    if: "!contains(github.event.head_commit.message, 'nodeploy')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}
          architecture: $${{ matrix.arch }}
      - name: Install poetry
        run: pip install poetry
      - name: Install requirements
        run: poetry install --with wheel_builder
      - name: Build package
        run: poetry build -f wheel
      - name: Test package
        run: poetry run test
      - name: publish to pypi
        run: poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
